Add Fluid support for AE2
SquidDev-CC/ccjam-2016 pull request #249
Opened 2020-01-27 20:25 UTC by fionera

A quick implementation of #247

2020-01-27 21:32 UTC, SquidDev requested changes
Thank you very much for adding this! I know Plethora isn't the easiest codebase to understand.

I've just left one minor nitpick, but otherwise it looks good. Thank you!

2020-01-27 21:32 UTC, SquidDev commented on src/main/java/org/squiddev/plethora/integration/appliedenergistics/MetaAppliedEnergistics.java
> +	private static final MetaFluidStack META_FLUID_STACK = new MetaFluidStack();
Can you refactor the `MetaFluidStack.getMeta` into a static method (which the instance method just delegates too)? Just saves us having to instantiate it here.

2020-01-27 22:33 UTC, SquidDev approved these changes

2020-01-27 22:39 UTC, merged

2020-01-27 22:42 UTC, SquidDev commented
Merged. Thank you very much!

2020-12-20 18:49 UTC, pipe0482 commented
I was playing with your mod and I love it, however I needed to query my system for fluids and found that it's not supported. I found this PR but noticed it was merged shortly after the last release, so are there any plans of releasing a new version? Thanks!