Add Basic Buildcraft support
SquidDev-CC/ccjam-2016 pull request #252
Opened 2020-02-18 18:22 UTC by fionera

This PR adds support for all interactions that can be done with Gates in Buildcraft. Sadly not all Blocks implement the needed Interfaces or I just didnt saw it.

2020-02-18 22:25 UTC, SquidDev requested changes
Thank you very much for the PR!

Just left a couple of comments on places where annotation magic can be used or isn't needed, otherwise looks really good.

2020-02-18 22:25 UTC, SquidDev commented on src/main/java/org/squiddev/plethora/integration/buildcraft/TileControllable.java
> +		try {
I _think_ you can use `IControllable.Mode` directly on the argument. We definitely do it for other enums:

https://github.com/SquidDev-CC/plethora/blob/527d945ab4c69514a63d2a04e2fcb767b8cfb3f8/src/main/java/org/squiddev/plethora/integration/rf/MethodsEnergy.java#L30

2020-02-18 22:25 UTC, SquidDev commented on src/main/java/org/squiddev/plethora/integration/buildcraft/TileControllable.java
> +@Injects(BCCore.MODID)
You don't need `@Injects` if you've only got methods inside the class. `@Injects` is used for fields.

2020-02-19 13:30 UTC, fionera commented
I did both changes but cant test them currently because my OpenGL is suddently broken. Will push when its tested ^^

2020-02-21 13:43 UTC, SquidDev approved these changes

2020-02-21 13:44 UTC, merged

2020-02-21 13:44 UTC, SquidDev commented
Thank you very much!

2020-02-21 13:44 UTC, fionera commented
That was fast :) Thanks for merging. Gonna backport it now to support the older CC:T Version I use ^^